version: '3'

services:
  postgres:
    container_name: 'postgres'
    image: 'postgres'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'

  app:
    container_name: 'app'
    image: 'quarkus-rest-and-jpa'
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres/postgres
    ports:
      - '8080:8080'
